[package]
name = "Jour05"
version = "0.1.0"
authors = ["Alexandre Adolphe <alexandre.adolphe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
regex = "1"
num = "0.3.1"
